apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "3000"
  NODE_ENV: "development"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USERNAME: "smartcity"
  DB_NAME: "smartcity"
  JWT_EXPIRES_IN: "7d"
  COOKIE_NAME: "auth_token"
  FRONTEND_URL: "http://localhost:5173"